### ISSUE TITLE
[EPIC] Ban/Unban flows 

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-app#13034]
Issue to review the implementation of ban/unban flows as discussed with @benjthayer and @mprakhov. Ban/Unban functions were recently found to move the user to an inbetween state not fully one or the other. Design for what a community should appear like to a banned user is also missing.

Unban Figma: https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=3250-369531&mode=design&t=jjuJaHJ0zHngpddl-4

Control node online/offline: https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=35910-617433&mode=design&t=jjuJaHJ0zHngpddl-4

Mobile design: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7674-521411&mode=design&t=bhBrRFsgWzdUrPfz-4

Related UI epic: https://github.com/status-im/status-desktop/issues/11649

tickets:
- [x] https://github.com/status-im/status-desktop/issues/13596
- [x] https://github.com/status-im/status-desktop/issues/13610
- [x] https://github.com/status-im/status-desktop/issues/13608
- [x] https://github.com/status-im/status-desktop/issues/13597
- [x] https://github.com/status-im/status-desktop/issues/13454
- [x] https://github.com/status-im/status-desktop/issues/13453
- [x] https://github.com/status-im/status-desktop/issues/12066
- [ ] https://github.com/status-im/status-desktop/issues/12067
- [ ] https://github.com/status-im/status-desktop/issues/11777
- [x] https://github.com/status-im/status-desktop/issues/13654

# 1. Ban

## 1.1 Owner/TokenMaster/Admin initiating the ban
* Hovering over a member in the community members list displays the “Ban” button
* Clicking on the ban button displays a popup

### 1.1.1 Ban popup
* Title: “Ban [member displayname]”
* X to close. Clicking on X closes the pop-up
* Text: Are you sure you want to ban [display name] from [community name]?
* Toggle with label: Delete all messages posted by the user
* “Cancel” button closes the pop-up

**1.1.1.1 If the control node is offline**
* Clicking the “Ban [display name]” button replaces the “Ban” button with the “Ban pending...” label. When the control node comes online the member is moved from the “All Members” list to the “Banned” list.

**1.1.1.2 If the control node is online**
* Clicking the "Ban [display name]" button moves the member from the “All Members” list to the “Banned” list.
* If “Delete all messages posted by the user” was selected, all the member’s messages are removed from the community
* If “Delete all messages posted by the user” was not selected, all the member’s messages persist in the community
* Member list and count shown to community is updated to not show the member

## 1.2 Other TokenMasters/Admins/Owner
* While the control node is offline the members list displays the appropriate “Ban pending...” labels.
* Any attempted ban before list is updated is handled appropriately.
* When the control node is online the member lists update to reflect the bans applied.

## 1.3 Banned community member
* All channels and community message content is hidden from the banned member *design needed
* “You were banned from [community name]” is displayed in place of the join button
* The input field is disabled. “You need to join this community to send messages” is displayed in the input field.

### 1.3.1 Unknown:

- Is there a toast on ban?
- Is there a notification added on ban?
- What to display while all channels are hidden?
- What happens to any messages sent by a banned member after the ban is initiated but before the ban is applied their client?

# 2. Unban

## 2.1 Owner/TokenMaster/Admin initiating the unban

- Hovering over a banned member on the “Banned” list displays the “Unban” button
- If the control node is offline, clicking on the “Unban” replaces the "Unban" button with the "Unban pending..." label *design needed
- If the control node is online, clicking on the “Unban” button unbans the member. The member is moved from the “Banned” list to the “All Members” list. The Member list and count shown to community is updated to show the member

## 2.2 Other TokenMasters/Admins
- While the control node is offline the members list displays the appropriate “Unban pending...” labels.
- Any attempted unban before the list is updated is handled appropriately.
- When the control node is online the member lists update to reflect the bans applied.

## 2.3 Unbanned community member
- User receives a toast: “You have been unbanned from [community name]!
- User receives a notification “You have been unbanned from [community name]!
- User automatically rejoins the community if they still meet the criteria of any applicable permissions.

**Comment by anastasiyaig** [comment]
i put it to 0.16 but not sure how realistic / urgent it is @John-44 @iurimatias

**Comment by John-44** [comment]
@benjthayer mentioning you here so you can take a look at the design items glitchminer mentioned in the issue report when you are back from holls

**Comment by John-44** [comment]
> i put it to 0.16 but not sure how realistic / urgent it is @John-44 @iurimatias

If it can't fit into 0.16 it should definitely be prioritized for 0.17.  I'm not the right person to comment on how realistic it is for 0.16 but my intuition is that it might not be possible to fit into 0.16 given all the other items scheduled for this milestone.  But this is up to @iurimatias

**Comment by benjthayer** [comment]
Full flows for the following have been added to the Kuba Communities file. These include:

**From the admin perspective:**
- Banning, unbanning and kicking

**From the member perspective:** 
- Being banned and unbanned 
- Being kicked
- Losing community membership due to sending requisite tokens / removing accounts or keypairs that hodl requisite tokens 
- Losing community membership due to a change in token requirements

**A couple of key points covered in the flows:**

**From the admin side**
- Added the ability for an admin to delete all of a user's messages after the ban event (from banned tab)
- Unbanning a user does not result in the automatic rejoining of that user to the community - the banned user must manually rejoin

**From the community member side**
- When a user is banned or kicked, the community should disappear from the community nav bar and the next community down should be selected (unless there are no other communities in the nav bar in which case the `Find community` page is selected).
- If a user is banned from the community, they should not be able to see or search for the community in the `Find community` page
- If the user navigates to the community while they are banned (eg via a share link), they will see a banned state for that community.
- Also covered in the flows is what the user sees if they lose access to the community due to a) edits to token gating requirements and b) loss of access due to sending tokens required for access or removing accounts/keypairs that contain tokens required for access

Figma:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=51860-257070&mode=design&t=pzq70E9CXbiufWaG-4

**Comment by mprakhov** [comment]
@benjthayer just to clarify - do we not want to see deleted msgs info when we ban someone with deleting all his messages?

![image](https://github.com/status-im/status-desktop/assets/117639195/e8a44d06-ef84-4419-b98c-dc6c1ea273e3)

**Comment by jrainville** [comment]
Closing as done. Only two small issues are left
